export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const ARTICLE_SUBMITTED = 'ARTICLE_SUBMITTED';
export const SETTINGS_SAVED = 'SETTINGS_SAVED';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const SETTINGS_PAGE_UNLOADED = 'SETTINGS_PAGE_UNLOADED';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const GEAR_ITEM_PAGE_LOADED = 'GEAR_ITEM_PAGE_LOADED';
export const GEAR_ITEM_PAGE_UNLOADED = 'GEAR_ITEM_PAGE_UNLOADED';
export const GEARS_PAGE_LOADED = 'GEARS_PAGE_LOADED';
export const GEARS_PAGE_UNLOADED = 'GEARS_PAGE_UNLOADED';
export const GEARS_LIST_PAGE_LOADED = 'GEARS_LIST_PAGE_LOADED';
export const GEARS_LIST_PAGE_UNLOADED = 'GEARS_LIST_PAGE_UNLOADED';
export const ARTICLE_PAGE_LOADED = 'ARTICLE_PAGE_LOADED';
export const ARTICLE_PAGE_UNLOADED = 'ARTICLE_PAGE_UNLOADED';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const ARTICLE_FAVORITED = 'ARTICLE_FAVORITED';
export const ARTICLE_UNFAVORITED = 'ARTICLE_UNFAVORITED';
export const SET_PAGE = 'SET_PAGE';
export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER';
export const CHANGE_TAB = 'CHANGE_TAB';
export const CHANGE_DETAIL_TAB = 'CHANGE_DETAIL_TAB';
export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED';
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED';
export const PEOPLE_PAGE_LOADED = 'PEOPLE_PAGE_LOADED';
export const PEOPLE_PAGE_UNLOADED = 'PEOPLE_PAGE_UNLOADED';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const EDITOR_PAGE_LOADED = 'EDITOR_PAGE_LOADED';
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED';
export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const UPDATE_FIELD_EDITOR = 'UPDATE_FIELD_EDITOR';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const PROFILE_FAVORITES_PAGE_UNLOADED = 'PROFILE_FAVORITES_PAGE_UNLOADED';
export const PROFILE_FAVORITES_PAGE_LOADED = 'PROFILE_FAVORITES_PAGE_LOADED';

export const PROFILE_SETTINGS_SAVED = 'PROFILE_SETTINGS_SAVED';
export const PROFILE_SETTINGS_PAGE_LOADED = 'PROFILE_SETTINGS_PAGE_LOADED';
export const PROFILE_SETTINGS_PAGE_UNLOADED = 'PROFILE_SETTINGS_PAGE_UNLOADED';

export const PROFILE_DISPLAY_FOLLOWED = 'PROFILE_DISPLAY_FOLLOWED';
export const PROFILE_DISPLAY_UNFOLLOWED = 'PROFILE_DISPLAY_UNFOLLOWED';

export const SUBSCRIBE_NEW = 'SUBSCRIBE_NEW';
export const SUBSCRIBE_UNLOADED = 'SUBSCRIBE_UNLOADED';
export const UPDATE_SUBSCRIBE_NEW_EMAIL = 'UPDATE_SUBSCRIBE_NEW_EMAIL';

export const BRANDS_PAGE_LOADED = 'BRANDS_PAGE_LOADED';
export const BRANDS_PAGE_UNLOADED = 'BRANDS_PAGE_UNLOADED';

export const PEOPLE_PAGE_GEAR_SECTION_LOADED = 'PEOPLE_PAGE_GEAR_SECTION_LOADED';
export const PEOPLE_PAGE_GEAR_SECTION_UNLOADED = 'PEOPLE_PAGE_GEAR_SECTION_UNLOADED';

export const GEARS_LIST_SET_PAGE = 'GEARS_LIST_SET_PAGE';
